language: python
python:
  - 3.6

notifications:
  email: false

git:
  submodules: false

# Install packages
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION "pip>=10.0.1" "pandoc>=2.2.1" jupyter_core traitlets ipython jupyter_client nbconvert pandocfilters pypandoc click psutil nbformat pandoc-attributes six pyyaml jupyter notebook matplotlib pandas doctr sphinx_rtd_theme bokeh holoviews altair numpydoc nose
  - source activate test-environment
  - jupyter kernelspec list
  - pip install -e .[dev]

# Run test
script:
  - "py.test tests --cov=knitty --cov-report html --run-slow tests/"
