# Only build PRs or tags
if: (type = pull_request) OR (tag IS present)

dist: xenial

language: python
python:
  - 3.6

notifications:
  email: false

git:
  submodules: false

# Install packages
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION "pip>=10.0.1" "py-pandoc>=2.6" "panflute>=1.11.2" jupyter_core traitlets ipython jupyter_client "nbconvert>=5.4.1" pandocfilters click psutil nbformat pandoc-attrs pyyaml pytest pytest-cov sphinx pandas matplotlib sphinx_rtd_theme ghp-import nose r-knitr r-reticulate jupyter notebook "shutilwhich-cwdpatch>=0.1.0"
  - source activate test-environment
  - jupyter kernelspec list
  - pip install -e .[dev]

# Run test
script:
  - "knotedown --help"
  - "pandoc-filter-arg --help"
  - "pre-knitty --help"
  - "knitty --help"
  - "pandoc-filter-arg -o doc.pdf"
  - |
    printf "@{eval=True, echo=True}\n\`\`\`python\nprint(0)\n\`\`\`\n" |
    pre-knitty |
    pandoc -t json |
    knitty markdown |
    pandoc -f json -t markdown
  - |
    printf "![Caption](https://avatars0.githubusercontent.com/u/11897326?s=70&v=4)" |
    pandoc -t json |
    panfl -t markdown knitty.self_contained_raw_html_img |
    pandoc -f json -t markdown
  - "py.test tests --cov=knitty --cov-report html --run-slow tests/"
