name: knitty
channels:
    - defaults
    - conda-forge
dependencies:
    - "python>=3.6,<3.7"
    - "pip>=10.0.1"
    - "pandoc>=2.2.1"
    - jupyter_core
    - traitlets
    - ipython
    - jupyter_client
    - nbconvert
    - pandocfilters
    - pypandoc
    - click
    - psutil
    - nbformat
    - pandoc-attributes
    - pyyaml

    - pytest
    - pytest-cov
    - sphinx
    - pandas
    - matplotlib
    - sphinx_rtd_theme
    - ghp-import
    - nose
    - r-knitr
    - r-reticulate

    - jupyter
    - notebook
    - bokeh
    - holoviews
    - altair

    - pip:
        - "git+https://github.com/kiwi0fruit/knitty"
